# Generated by Django 5.0.7 on 2024-07-26 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Введите телефон в виде "+1234567890", не более 15 цифр.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('Ordered', 'Заказан'), ('InProcess', 'В обработке'), ('InDelivery', 'Доставляется'), ('Completed', 'Завершён')], default='Ordered', max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
